const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();
  await page.goto('http://localhost:8081', { waitUntil: 'networkidle' });
  await page.waitForTimeout(1000);
  await page.fill('input[placeholder*="Email"], input[placeholder*="email"]', 'admin@nvc.org');
  await page.fill('input[placeholder*="Password"]', 'admin123');
  const loginLocator = page.getByText(/log\s*in/i).first();
  await loginLocator.click();
  await page.waitForTimeout(2000);
  const bodyText = await page.textContent('body');
  const re = /dashboard|admin.*panel|user.*management|approvals/i;
  console.log('body text length', bodyText?.length);
  console.log('regex source', re.source);
  console.log('regex flags', re.flags);
  console.log('regex test', re.test(bodyText || ''));
  console.log('contains dashboard', /dashboard/i.test(bodyText || ''));
  console.log('contains admin dashboard', /admin dashboard/i.test(bodyText || ''));
  console.log('contains approvals', /approvals/i.test(bodyText || ''));
  await browser.close();
})();
