const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();
  await page.goto('http://localhost:8081', { waitUntil: 'networkidle' });
  await page.waitForTimeout(1000);
  await page.fill('input[placeholder*="Email"], input[placeholder*="email"]', 'admin@nvc.org');
  await page.fill('input[placeholder*="Password"]', 'admin123');
  const loginLocator = page.getByText(/log\s*in/i).first();
  await loginLocator.click();
  await page.waitForTimeout(2000);
  const bodyText = await page.textContent('body');
  console.log('url:', page.url());
  console.log('title:', await page.title());
  console.log('body includes dashboard:', /dashboard/i.test(bodyText));
  console.log('body includes admin dashboard:', /admin dashboard/i.test(bodyText));
  console.log('count dashboard text:', await page.getByText(/dashboard/i).count());
  console.log('count admin dashboard:', await page.getByText(/admin dashboard/i).count());
  console.log('count approvals:', await page.getByText(/approvals/i).count());
  await browser.close();
})();
